/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef MODGAUS01
#define MODGAUS01

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class ModGaus01 : public RooAbsPdf {
public:
  ModGaus01() {} ; 
  ModGaus01(const char *name, const char *title,
	      RooAbsReal& _m,
	      RooAbsReal& _m0,
	      RooAbsReal& _v0,
	      RooAbsReal& _s0,
	      RooAbsReal& _s1);
  ModGaus01(const ModGaus01& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new ModGaus01(*this,newname); }
  inline virtual ~ModGaus01() { }

protected:

  RooRealProxy m ;
  RooRealProxy m0 ;
  RooRealProxy v0 ;
  RooRealProxy s0 ;
  RooRealProxy s1 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(ModGaus01,1) // Your description goes here...
};
 
#endif
