/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef MODTHREEGAUS
#define MODTHREEGAUS

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class ModThreeGaus : public RooAbsPdf {
public:
  ModThreeGaus() {} ; 
  ModThreeGaus(const char *name, const char *title,
	      RooAbsReal& _m,
	      RooAbsReal& _m0,
	      RooAbsReal& _v0,
	      RooAbsReal& _v1,
	      RooAbsReal& _v2,
	      RooAbsReal& _s0,
	      RooAbsReal& _s1,
	      RooAbsReal& _s2);
  ModThreeGaus(const ModThreeGaus& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new ModThreeGaus(*this,newname); }
  inline virtual ~ModThreeGaus() { }

protected:

  RooRealProxy m ;
  RooRealProxy m0 ;
  RooRealProxy v0 ;
  RooRealProxy v1 ;
  RooRealProxy v2 ;
  RooRealProxy s0 ;
  RooRealProxy s1 ;
  RooRealProxy s2 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(ModThreeGaus,1) // Your description goes here...
};
 
#endif
