/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef GAUSCB
#define GAUSCB

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class GausCB : public RooAbsPdf {
public:
  GausCB() {} ; 
  GausCB(const char *name, const char *title,
	      RooAbsReal& _m,
	      RooAbsReal& _mean,
	      RooAbsReal& _gaus_std,
	      RooAbsReal& _cb_std,
	      RooAbsReal& _cb_alpha,
	      RooAbsReal& _cb_n,
	      RooAbsReal& _cb_frac);
  GausCB(const GausCB& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new GausCB(*this,newname); }
  inline virtual ~GausCB() { }

protected:

  RooRealProxy m ;
  RooRealProxy mean ;
  RooRealProxy gaus_std ;
  RooRealProxy cb_std ;
  RooRealProxy cb_alpha ;
  RooRealProxy cb_n ;
  RooRealProxy cb_frac ;
  
  Double_t evaluate() const ;

private:

  ClassDef(GausCB,1) // Your description goes here...
};
 
#endif
