/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef MODGAUS11
#define MODGAUS11

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class ModGaus11 : public RooAbsPdf {
public:
  ModGaus11() {} ; 
  ModGaus11(const char *name, const char *title,
	      RooAbsReal& _m,
	      RooAbsReal& _m0,
	      RooAbsReal& _v0,
	      RooAbsReal& _v1,
	      RooAbsReal& _s0,
	      RooAbsReal& _s1);
  ModGaus11(const ModGaus11& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new ModGaus11(*this,newname); }
  inline virtual ~ModGaus11() { }

protected:

  RooRealProxy m ;
  RooRealProxy m0 ;
  RooRealProxy v0 ;
  RooRealProxy v1 ;
  RooRealProxy s0 ;
  RooRealProxy s1 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(ModGaus11,1) // Your description goes here...
};
 
#endif
