/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "ModGaus21.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(ModGaus21);

 ModGaus21::ModGaus21(const char *name, const char *title, 
                        RooAbsReal& _m,
                        RooAbsReal& _m0,
                        RooAbsReal& _v0,
                        RooAbsReal& _v1,
                        RooAbsReal& _s0,
                        RooAbsReal& _s1,
                        RooAbsReal& _s2) :
   RooAbsPdf(name,title), 
   m("m","m",this,_m),
   m0("m0","m0",this,_m0),
   v0("v0","v0",this,_v0),
   v1("v1","v1",this,_v1),
   s0("s0","s0",this,_s0),
   s1("s1","s1",this,_s1),
   s2("s2","s2",this,_s2)
 { 
 } 


 ModGaus21::ModGaus21(const ModGaus21& other, const char* name) :  
   RooAbsPdf(other,name), 
   m("m",this,other.m),
   m0("m0",this,other.m0),
   v0("v0",this,other.v0),
   v1("v1",this,other.v1),
   s0("s0",this,other.s0),
   s1("s1",this,other.s1),
   s2("s2",this,other.s2)
 { 
 } 

 Double_t ModGaus21::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
  Double_t width(0), power(0);
  Double_t alpha = 2*(m - 100)/(180-100) - 1;
  vector<double> s = {s0,s1,s2};
  vector<double> v = {v0,v1};
  for(size_t is = 0; is < s.size(); is++) width += s[is]*legendre(is,alpha);
  for(size_t iv = 0; iv < v.size(); iv++) power += v[iv]*legendre(iv,alpha);
  return exp(-1*pow(fabs((m-m0)/width), power));
 } 
