/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef MODGAUS21
#define MODGAUS21

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class ModGaus21 : public RooAbsPdf {
public:
  ModGaus21() {} ; 
  ModGaus21(const char *name, const char *title,
	    RooAbsReal& _m,
	    RooAbsReal& _m0,
	    RooAbsReal& _v0,
	    RooAbsReal& _v1,
	    RooAbsReal& _s0,
	    RooAbsReal& _s1,
	    RooAbsReal& _s2);
  ModGaus21(const ModGaus21& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new ModGaus21(*this,newname); }
  inline virtual ~ModGaus21() { }

protected:

  RooRealProxy m ;
  RooRealProxy m0 ;
  RooRealProxy v0 ;
  RooRealProxy v1 ;
  RooRealProxy s0 ;
  RooRealProxy s1 ;
  RooRealProxy s2 ;

  Double_t evaluate() const ;

private:

  ClassDef(ModGaus21,1) // Your description goes here...
};
 
#endif
